# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6e60dae5b591e333023daf9e3d96044e6c7fb877a3b9d90500a662ac33325f03dab5396a6d45475ad980addfdbab32fc32bea09e80620a6290a47ea29c683ee

test:
  secret_key_base: 61c7e652a92c878b1ae56de7586bc8dae08bf085d1d5b9424a5aca9ddde7c343ebe138214b6a96fc034eeb1be6ef96c634483c6e25d53f6cb01f7bfc9eef04be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
